services:
  api:
    image: aioz-roadmap:latest
    ports:
      - "8077:9191"
    volumes:
      - roadmap_data:/app/db
      - ./configs:/app/configs:ro
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # max 10MB per log file
        max-file: "3"      # keep max 3 rotated files = 30MB total

volumes:
  roadmap_data:
