Server:
  Name: "Roadmap Service"
  Host: "0.0.0.0"
  Port: 9191
  Env: "staging"
  AllowOrigins:
    - "http://localhost:3000"
    - "https://lp.attoaioz.cyou"
    - "https://aioz-network-lp-git-develop-aioz-networks-projects.vercel.app"
SQLite:
  Directory: "db"
  DatabaseName: "roadmap.db"
JWT:
  SigningKey: "a-string-secret-at-least-256-bits-long"
SeedAdmin:
  Username: "admin"
  Password: "admin"
W3Storage:
  AccessKey: "FT3UVQORELK2EQ25OE3643WUY4"
  SecretKey: "G4NFHHPDRM6MCKNEOUIV4SMW7XBUXDMVKQTS67CAE63SA5GJJZDQ"
  Endpoint: "https://s3-storage.attoaioz.cyou"
  PublicEndpoint: "https://api-pub-storage.attoaioz.cyou"
  Bucket: "roadmap"
  PathFolder: "thumbnail"
