Server:
  Name: "Roadmap Service"
  Host: "0.0.0.0"
  Port: 9191
  Env: "local"
  AllowOrigins:
    - "http://localhost:3000"
    - "https://aioz-network-lp-git-develop-aioz-networks-projects.vercel.app"
SQLite:
  Directory: "db"
  DatabaseName: "roadmap.db"
JWT:
  SigningKey: "a-string-secret-at-least-256-bits-long"
SeedAdmin:
  Username: "admin"
  Password: "admin"
